### ISSUE TITLE
Crash in LED driver using netdev

### ISSUE THREAD

**Issue by CRCinAU** [riptidewave93/LEDE-APU2#8] opened 2016-10-25 15:56 UTC
Crash message:

```
[ 1077.853549] INFO: rcu_sched self-detected stall on CPU
[ 1077.858748]  0-...: (77908 ticks this GP) idle=7bd/140000000000002/0 softirq=5757/5757 fqs=77896
[ 1077.867646]   (t=78012 jiffies g=998 c=997 q=498)
[ 1077.872401] Task dump for CPU 0:
[ 1077.875651] netifd          R  running task        0  1205      1 0x00000008
[ 1077.882782]  ffffffff81610dc0 ffffffff8109e1b1 ffff88011ec14780 ffffffff81610dc0
[ 1077.890311]  ffffffff81610dc0 00000000000001f2 ffffffff810a13b9 0000000000627675
[ 1077.897833]  ffff8800db9acb40 0000000000984d56 ffff88011ec03c40 0000000000000082
[ 1077.905355] Call Trace:
[ 1077.907819]  <IRQ>  [<ffffffff8109e1b1>] ? rcu_dump_cpu_stacks+0x71/0xa0
[ 1077.914579]  [<ffffffff810a13b9>] ? rcu_check_callbacks+0x409/0x6a0
[ 1077.920869]  [<ffffffff810a8cb7>] ? update_wall_time+0x3f7/0x630
[ 1077.926913]  [<ffffffff810a2c4d>] ? update_process_times+0x2d/0x50
[ 1077.933127]  [<ffffffff810af031>] ? tick_sched_timer+0x41/0x160
[ 1077.939070]  [<ffffffff810a3476>] ? __hrtimer_run_queues+0xa6/0x140
[ 1077.945381]  [<ffffffff810a3721>] ? hrtimer_interrupt+0x91/0x180
[ 1077.951412]  [<ffffffff8102ce4e>] ? smp_trace_apic_timer_interrupt+0x5e/0x90
[ 1077.958484]  [<ffffffff814554ff>] ? apic_timer_interrupt+0x7f/0x90
[ 1077.964695]  [<ffffffff81091c76>] ? native_queued_spin_lock_slowpath+0x146/0x160
[ 1077.972119]  [<ffffffff814543f8>] ? _raw_spin_lock+0x18/0x20
[ 1077.977808]  [<ffffffffa008b8e2>] ? igb_update_stats+0xe62/0xec0 [igb]
[ 1077.984364]  [<ffffffff8138589a>] ? dev_get_stats+0x4a/0xf0
[ 1077.989962]  [<ffffffff81365330>] ? led_mode_show+0xb0/0xb0
[ 1077.995558]  [<ffffffff8136537e>] ? netdev_trig_timer+0x4e/0xc0
[ 1078.001507]  [<ffffffff81365330>] ? led_mode_show+0xb0/0xb0
[ 1078.007103]  [<ffffffff810a29d1>] ? call_timer_fn.isra.4+0x11/0x70
[ 1078.013309]  [<ffffffff810a2b60>] ? run_timer_softirq+0x130/0x1f0
[ 1078.019435]  [<ffffffff81067e16>] ? __do_softirq+0xc6/0x1d0
[ 1078.025033]  [<ffffffff8106803f>] ? irq_exit+0x6f/0x80
[ 1078.030198]  [<ffffffff8102ce53>] ? smp_trace_apic_timer_interrupt+0x63/0x90
[ 1078.037282]  [<ffffffff814554ff>] ? apic_timer_interrupt+0x7f/0x90
[ 1078.043480]  <EOI>  [<ffffffffa0084f01>] ? igb_rd32+0x11/0x2760 [igb]
[ 1078.049998]  [<ffffffffa008ab93>] ? igb_update_stats+0x113/0xec0 [igb]
[ 1078.056551]  [<ffffffffa008b8f1>] ? igb_update_stats+0xe71/0xec0 [igb]
[ 1078.063101]  [<ffffffff8138589a>] ? dev_get_stats+0x4a/0xf0
[ 1078.068697]  [<ffffffff813a18df>] ? netstat_show.isra.12+0x4f/0xa0
[ 1078.074904]  [<ffffffff812a57e4>] ? dev_attr_show+0x14/0x40
[ 1078.080511]  [<ffffffff811502cd>] ? sysfs_kf_seq_show+0xad/0x120
[ 1078.086541]  [<ffffffff811218a9>] ? seq_read+0xc9/0x370
[ 1078.091792]  [<ffffffff81103b7e>] ? __vfs_read+0x1e/0xd0
[ 1078.097132]  [<ffffffff81117205>] ? dput+0x25/0x220
[ 1078.102036]  [<ffffffff8111c49f>] ? __alloc_fd+0x3f/0x180
[ 1078.107461]  [<ffffffff811041a4>] ? vfs_read+0x74/0xf0
[ 1078.112625]  [<ffffffff811049fa>] ? SyS_read+0x3a/0x90
[ 1078.117795]  [<ffffffff8145482e>] ? entry_SYSCALL_64_fastpath+0x12/0x71
```

Seems to happen pretty quickly if you have the LED triggered by a net device.

**Comment by riptidewave93** [comment] 2016-10-26 05:30
@CRCinAU This looks like an upstream crash with the trigger for the LED, as it errors within the igb driver and not the LED driver. Is this based on latest HEAD?

EDIT: Working fine here.

```
root@lede:/# cat /etc/config/system 

config system
        option hostname 'lede'
        option timezone 'UTC'
        option ttylogin '0'
        option log_size '64'
        option urandom_seed '0'

config timeserver 'ntp'
        option enabled '1'
        option enable_server '0'
        list server '0.lede.pool.ntp.org'
        list server '1.lede.pool.ntp.org'
        list server '2.lede.pool.ntp.org'
        list server '3.lede.pool.ntp.org'

config led 'led_wlan0'
        option sysfs 'apu2:green:led2'
        option trigger 'netdev'
        option dev 'eth0'
        option name 'WAN'
        option default '1'
        option mode 'link tx rx'

config led 'led_wlan1'
        option name 'WLAN1'
        option sysfs 'apu2:green:led3'
        option trigger 'phy1tpt'
        option default '0'
```

**Comment by CRCinAU** [comment] 2016-10-26 05:45
This is using the latest lede master & your upstream branch. This uses kernel 4.4.27 atm.

Out of interest, does yours still work if the interface is unplugged and you have it assigned?

**Comment by riptidewave93** [comment] 2016-10-26 05:50
I am using it with eth0 (WAN port) and it continues to work if the cable is unplugged/replugged in. Mind if I ask your build revision? I am testing on r1954

**Comment by CRCinAU** [comment] 2016-10-26 05:51
I'm using r1967 from my new nightlies stream: http://openwrt.crc.id.au/r1967/apu2/

EDIT: For what its worth, without the LEDs configured as netdev (in fact, unconfigured):

```
# uptime
 16:53:16 up 13:51,  load average: 0.00, 0.00, 0.00
```

**Comment by riptidewave93** [comment] 2016-10-26 06:00
@CRCinAU Interesting, I am not seeing any major code changes upstream between then and now that would explain this behavior. If you try building using the build.sh script (and it's checkout for r1594) does it work as expected? Also, are you using any custom toolchain for your build?

**Comment by CRCinAU** [comment] 2016-10-26 06:01
If you can jump into #lede-dev, I can have a quick chat about it?

**Comment by riptidewave93** [comment] 2016-10-26 07:20
After some trial and error, this error was unable to be reproduced. Closing for now until a pattern/cause can be found.

**Closed as completed by riptidewave93** 2016-10-26 07:20 UTC

**Comment by CRCinAU** [comment] 2016-10-26 09:26
I hate to say it, but it happened again after our troubleshooting :(

Not sure if it matters, but I was messing around with the firewall in luci, then boom, it was all over. When the crash occurs, the LED is always ON (I use default off, on for activity).

From /etc/config/system:

```
config led
        option default '0'
        option name 'eth2'
        option trigger 'netdev'
        option dev 'eth2'
        option mode 'tx rx'
        option sysfs 'apu2:green:led3'

config led
        option default '0'
        option name 'eth0'
        option sysfs 'apu2:green:led2'
        option trigger 'netdev'
        option dev 'eth0'
        option mode 'tx rx'
```

Crash message from dmesg

```
[   38.081751] random: nonblocking pool is initialized
[ 8818.988014] INFO: rcu_sched self-detected stall on CPU
[ 8818.993222]  0-...: (1 GPs behind) idle=96f/140000000000002/0 softirq=559757/559757 fqs=5998
[ 8819.001779]   (t=6000 jiffies g=3776 c=3775 q=751)
[ 8819.006627] Task dump for CPU 0:
[ 8819.009879] netifd          R  running task        0  1213      1 0x00000008
[ 8819.017000]  ffffffff81610dc0 ffffffff8109e1b1 ffff88011ec14780 ffffffff81610dc0
[ 8819.024524]  ffffffff81610dc0 00000000000002ef ffffffff810a13b9 00000000008f8589
[ 8819.032047]  ffff8800db3ec080 0000000000984d60 ffff88011ec03c40 0000000000000082
[ 8819.039568] Call Trace:
[ 8819.042051]  <IRQ>  [<ffffffff8109e1b1>] ? rcu_dump_cpu_stacks+0x71/0xa0
[ 8819.048828]  [<ffffffff810a13b9>] ? rcu_check_callbacks+0x409/0x6a0
[ 8819.055117]  [<ffffffff810a8cb7>] ? update_wall_time+0x3f7/0x630
[ 8819.061157]  [<ffffffff810a2c4d>] ? update_process_times+0x2d/0x50
[ 8819.067380]  [<ffffffff810af031>] ? tick_sched_timer+0x41/0x160
[ 8819.073320]  [<ffffffff810a3476>] ? __hrtimer_run_queues+0xa6/0x140
[ 8819.079612]  [<ffffffff810a3721>] ? hrtimer_interrupt+0x91/0x180
[ 8819.085645]  [<ffffffff8102ce4e>] ? smp_trace_apic_timer_interrupt+0x5e/0x90
[ 8819.092718]  [<ffffffff814554ff>] ? apic_timer_interrupt+0x7f/0x90
[ 8819.098933]  [<ffffffff81091c76>] ? native_queued_spin_lock_slowpath+0x146/0x160
[ 8819.106364]  [<ffffffff814543f8>] ? _raw_spin_lock+0x18/0x20
[ 8819.112066]  [<ffffffffa008b8e2>] ? igb_update_stats+0xe62/0xec0 [igb]
[ 8819.118621]  [<ffffffff8138589a>] ? dev_get_stats+0x4a/0xf0
[ 8819.124223]  [<ffffffff81365330>] ? led_mode_show+0xb0/0xb0
[ 8819.129815]  [<ffffffff8136537e>] ? netdev_trig_timer+0x4e/0xc0
[ 8819.135763]  [<ffffffff81365330>] ? led_mode_show+0xb0/0xb0
[ 8819.141367]  [<ffffffff810a29d1>] ? call_timer_fn.isra.4+0x11/0x70
[ 8819.147571]  [<ffffffff810a2b60>] ? run_timer_softirq+0x130/0x1f0
[ 8819.153709]  [<ffffffff81067e16>] ? __do_softirq+0xc6/0x1d0
[ 8819.159304]  [<ffffffff8106803f>] ? irq_exit+0x6f/0x80
[ 8819.164469]  [<ffffffff8102ce53>] ? smp_trace_apic_timer_interrupt+0x63/0x90
[ 8819.171539]  [<ffffffff814554ff>] ? apic_timer_interrupt+0x7f/0x90
[ 8819.177768]  <EOI>  [<ffffffffa0084f01>] ? igb_rd32+0x11/0x2760 [igb]
[ 8819.184272]  [<ffffffffa008aae1>] ? igb_update_stats+0x61/0xec0 [igb]
[ 8819.190747]  [<ffffffffa008b8f1>] ? igb_update_stats+0xe71/0xec0 [igb]
[ 8819.197293]  [<ffffffff8138589a>] ? dev_get_stats+0x4a/0xf0
[ 8819.202894]  [<ffffffff813a18df>] ? netstat_show.isra.12+0x4f/0xa0
[ 8819.209102]  [<ffffffff812a57e4>] ? dev_attr_show+0x14/0x40
[ 8819.214727]  [<ffffffff811502cd>] ? sysfs_kf_seq_show+0xad/0x120
[ 8819.220770]  [<ffffffff811218a9>] ? seq_read+0xc9/0x370
[ 8819.226026]  [<ffffffff81103b7e>] ? __vfs_read+0x1e/0xd0
[ 8819.231365]  [<ffffffff81117205>] ? dput+0x25/0x220
[ 8819.236276]  [<ffffffff8111c49f>] ? __alloc_fd+0x3f/0x180
[ 8819.241727]  [<ffffffff811041a4>] ? vfs_read+0x74/0xf0
[ 8819.246889]  [<ffffffff811049fa>] ? SyS_read+0x3a/0x90
[ 8819.252083]  [<ffffffff8145482e>] ? entry_SYSCALL_64_fastpath+0x12/0x71
```

**Comment by riptidewave93** [comment] 2016-10-26 10:14
@CRCinAU Hmm, makes me wonder if it's related to https://sourceforge.net/p/e1000/bugs/500/. Just for good measure, can you try setting the LEDs to "default" of 1 to see if it has any affect?

**Comment by CRCinAU** [comment] 2016-10-27 08:57
Set default = 1 and left it on through the day. When I got home tonight, I played again and sure enough, got a crash. Only recovery seems to be a power cycle.

```
[29275.271405] INFO: rcu_sched self-detected stall on CPU
[29275.276610]  0-...: (1 GPs behind) idle=f05/140000000000002/0 softirq=1483650/1483656 fqs=5992
[29275.285340]   (t=6000 jiffies g=5926 c=5925 q=207)
[29275.290186] Task dump for CPU 0:
[29275.293436] luci            R  running task        0  2155   1401 0x0000000c
[29275.300561]  ffffffff8164cf00 ffffffff8109e1c1 ffff88011ec14780 ffffffff8164cf00
[29275.308078]  ffffffff8164cf00 00000000000000cf ffffffff810a13c9 00000000006b524a
[29275.315599]  ffff8800db1560c0 0000000000984d56 ffff88011ec03c40 0000000000000082
[29275.323115] Call Trace:
[29275.325587]  <IRQ>  [<ffffffff8109e1c1>] ? rcu_dump_cpu_stacks+0x71/0xa0
[29275.332362]  [<ffffffff810a13c9>] ? rcu_check_callbacks+0x409/0x6a0
[29275.338812]  [<ffffffff810a8cc7>] ? update_wall_time+0x3f7/0x630
[29275.344840]  [<ffffffff810a2c5d>] ? update_process_times+0x2d/0x50
[29275.351049]  [<ffffffff810af041>] ? tick_sched_timer+0x41/0x160
[29275.356989]  [<ffffffff810a3486>] ? __hrtimer_run_queues+0xa6/0x140
[29275.363283]  [<ffffffff810a3731>] ? hrtimer_interrupt+0x91/0x180
[29275.369317]  [<ffffffff8102ce4e>] ? smp_trace_apic_timer_interrupt+0x5e/0x90
[29275.376387]  [<ffffffff814741ff>] ? apic_timer_interrupt+0x7f/0x90
[29275.382594]  [<ffffffff81091c86>] ? native_queued_spin_lock_slowpath+0x146/0x160
[29275.390025]  [<ffffffff814730d8>] ? _raw_spin_lock+0x18/0x20
[29275.395722]  [<ffffffffa008d902>] ? igb_update_stats+0xe62/0xec0 [igb]
[29275.402283]  [<ffffffff8138fcca>] ? dev_get_stats+0x4a/0xf0
[29275.407878]  [<ffffffff8136e4f0>] ? led_mode_show+0xb0/0xb0
[29275.413472]  [<ffffffff8136e53e>] ? netdev_trig_timer+0x4e/0xc0
[29275.419428]  [<ffffffff8136e4f0>] ? led_mode_show+0xb0/0xb0
[29275.425024]  [<ffffffff810a29e1>] ? call_timer_fn.isra.4+0x11/0x70
[29275.431241]  [<ffffffff810a2b70>] ? run_timer_softirq+0x130/0x1f0
[29275.437359]  [<ffffffff81067e26>] ? __do_softirq+0xc6/0x1d0
[29275.442952]  [<ffffffff8106804f>] ? irq_exit+0x6f/0x80
[29275.448111]  [<ffffffff8102ce53>] ? smp_trace_apic_timer_interrupt+0x63/0x90
[29275.455183]  [<ffffffff814741ff>] ? apic_timer_interrupt+0x7f/0x90
[29275.461382]  <EOI>  [<ffffffffa0086f01>] ? igb_rd32+0x11/0x2760 [igb]
[29275.467893]  [<ffffffffa008cfdd>] ? igb_update_stats+0x53d/0xec0 [igb]
[29275.474444]  [<ffffffffa008d911>] ? igb_update_stats+0xe71/0xec0 [igb]
[29275.481007]  [<ffffffff8138fcca>] ? dev_get_stats+0x4a/0xf0
[29275.486615]  [<ffffffff8146bf5b>] ? rtnl_fill_stats+0x17/0x128
[29275.492477]  [<ffffffff813a3735>] ? rtnl_fill_ifinfo+0x4c5/0xab0
[29275.498643]  [<ffffffff813a3e11>] ? rtnl_dump_ifinfo+0xf1/0x1e0
[29275.504594]  [<ffffffff813ba85d>] ? netlink_dump+0x10d/0x270
[29275.510280]  [<ffffffff813baf05>] ? __netlink_dump_start+0x125/0x160
[29275.516660]  [<ffffffff813a3d20>] ? rtnl_fill_ifinfo+0xab0/0xab0
[29275.522690]  [<ffffffff813a4888>] ? rtnetlink_rcv_msg+0x188/0x200
[29275.528808]  [<ffffffff813a3d20>] ? rtnl_fill_ifinfo+0xab0/0xab0
[29275.534841]  [<ffffffff813a4700>] ? rtnetlink_rcv+0x30/0x30
[29275.540435]  [<ffffffff813bcab3>] ? netlink_rcv_skb+0x73/0x90
[29275.546201]  [<ffffffff813a46ef>] ? rtnetlink_rcv+0x1f/0x30
[29275.551807]  [<ffffffff813bc466>] ? netlink_unicast+0x126/0x1d0
[29275.557762]  [<ffffffff813bc87b>] ? netlink_sendmsg+0x2ab/0x350
[29275.563726]  [<ffffffff8110f4c0>] ? path_lookupat+0xe0/0x100
[29275.569413]  [<ffffffff8137ed93>] ? SyS_sendto+0xe3/0x160
[29275.574847]  [<ffffffff81105857>] ? get_empty_filp+0xb7/0x160
[29275.580629]  [<ffffffff81105916>] ? alloc_file+0x16/0xa0
[29275.585972]  [<ffffffff8137cd82>] ? sock_alloc_file+0x92/0x110
[29275.591831]  [<ffffffff8147352e>] ? entry_SYSCALL_64_fastpath+0x12/0x71
```

**Comment by CRCinAU** [comment] 2016-10-27 09:17
Talk in #lede-dev seems to think that this may be a solution: http://nbd.name/igb-fix.patch

I'll add it to my nightly builds and test tomorrow.

**Comment by riptidewave93** [comment] 2016-10-27 11:43
Awesome, @CRCinAU let me know how it goes. If needed, I can add it to the repo for the time being until:
1. It's added to LEDE by nbd
2. It's fixed upstream and in the kernel used by x86_64

EDIT: Seems to build fine, for now it ha been added to the staging branch.

**Comment by CRCinAU** [comment] 2016-10-28 03:03
Ok, I've built this into r2024:
http://openwrt.crc.id.au/r2024/apu2/

Lets see how we go.

**Comment by Strykar** [comment] 2016-11-24 20:26
@CRCinAU No more crashes after applying http://nbd.name/igb-fix.patch?

**Comment by CRCinAU** [comment] 2016-11-25 00:09
Correct. Without the patch, having the LED trigger on ethernet traffic causes crashes. With the patch, all ok.

**Comment by rotanid** [comment] 2017-02-01 01:41
have you talked to nbd after this if he will include it in LEDE?

**Comment by CRCinAU** [comment] 2017-02-01 01:58
It has been mentioned multiple times to nbd that this patch works. If it still isn't in the LEDE repo or the upstream kernel, it probably needs someone more motivated than me to chase this up to get it completed.

**Comment by rotanid** [comment] 2017-02-01 23:08
```
00:04:10 <nbd > rotanid: the fix should not be necessary anymore
00:04:17 <nbd > i fixed ledtrig-netdev instead
```

so this patch should be obsolete

**Comment by CRCinAU** [comment] 2017-02-02 01:01
Do you happen to know if this was upstreamed to kernel.org? or only within the lede git repo?

**Comment by rotanid** [comment] 2017-02-02 01:09
@CRCinAU maybe ask him yourself on IRC freenode/#lede-dev ?

**Comment by CRCinAU** [comment] 2017-02-02 01:12
We're on opposite sides of the globe timezone wise - so we very rarely catch up at the same time. hence being so difficult to chase up / discuss.
